# Tugas 2 : Diskritasi

In [ ]:
from matplotlib import rcParams, cycler
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
plt.ion()

In [ ]:
dataset = "https://raw.githubusercontent.com/Zey21/dataset/main/Iris.csv"
data = pd.read_csv(dataset)

In [ ]:
data.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [ ]:
from sklearn.preprocessing import KBinsDiscretizer

In [ ]:
sepalLength = data.SepalLengthCm
sepalWidth = data.SepalWidthCm
petalLength = data.PetalLengthCm
petalWidth = data.PetalWidthCm
spesies = data.Species

In [ ]:
aa = sepalLength.values.reshape(-1,1)
ab = sepalWidth.values.reshape(-1,1)
ac = petalLength.values.reshape(-1,1)
ad = petalWidth.values.reshape(-1,1)
sp = spesies.values.reshape(-1,1)

In [ ]:
est = KBinsDiscretizer(n_bins=4, encode='ordinal', strategy='uniform')

In [ ]:
est.fit(aa)
est.fit(ab)
est.fit(ac)
est.fit(ad)

KBinsDiscretizer(encode='ordinal', n_bins=4, strategy='uniform')

In [ ]:
KBinsDiscretizer(...)

KBinsDiscretizer(n_bins=Ellipsis)

In [ ]:
xa = est.transform(aa)
xb = est.transform(ab)
xc = est.transform(ac)
xd = est.transform(ad)

In [ ]:
dataa1 = {'sepal_length':xa}
dataa2 = {'sepal_length':xb}
dataa3 = {'sepal_length':xc}
dataa4 = {'sepal_length':xd}

In [ ]:
fa = pd.DataFrame(xa,columns=['sepal_length'])
fb = pd.DataFrame(xb,columns=['sepal_width'])
fc = pd.DataFrame(xc,columns=['tepal_length'])
fd = pd.DataFrame(xd,columns=['tepal_width'])
spe = pd.DataFrame(sp,columns=['Species'])

In [ ]:
datalist = [fa, fb, fc, fd, spe]
pd.concat(datalist, axis=1)

     sepal_length  sepal_width  tepal_length  tepal_width         Species
0             3.0          3.0           2.0          0.0     Iris-setosa
1             3.0          3.0           2.0          0.0     Iris-setosa
2             3.0          3.0           2.0          0.0     Iris-setosa
3             3.0          3.0           2.0          0.0     Iris-setosa
4             3.0          3.0           2.0          0.0     Iris-setosa
..            ...          ...           ...          ...             ...
145           3.0          3.0           3.0          3.0  Iris-virginica
146           3.0          3.0           3.0          3.0  Iris-virginica
147           3.0          3.0           3.0          3.0  Iris-virginica
148           3.0          3.0           3.0          3.0  Iris-virginica
149           3.0          3.0           3.0          2.0  Iris-virginica

[150 rows x 5 columns]